### ISSUE TITLE
File not properly indexed

### ISSUE THREAD

**Issue by KirillOsenkov** [Ref12/Codex#130]
Searching for “SingletonHierarchyWindowService” yields the file with that name but the editor pane shows only “No definitions found.”

(from @amcasey)

**Comment by ljcollins25** [comment]
I did the search and found the file. That said, it is just raw text. Please re-open if we need to investigate why semantic info is not available.

**Comment by KirillOsenkov** [comment]
Yeah let’s look into the missing semantics.

**Comment by ljcollins25** [comment]
Can't find this file anymore. Any idea where its supposed to come from?

**Comment by KirillOsenkov** [comment]
No idea, let's close this then as not actionable.
