### ISSUE TITLE
Wrong source shown for `SAsyncServiceProvider

### ISSUE THREAD

**Issue by KirillOsenkov** [Ref12/Codex#132]
Search for `SAsyncServiceProvider

The lines in results don't match the lines in source file:

![image](https://user-images.githubusercontent.com/679326/45003763-8a01d380-af9a-11e8-8409-0c612ceedb5d.png)

**Comment by ljcollins25** [comment]
Just did the search, and it seems fine. Reopen  if you still have a repro.
