### ISSUE TITLE
Use correct branch name for NuGet.Client

### ISSUE THREAD

**Issue by KirillOsenkov** [Ref12/Codex#141]
Expected:
`https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Common/CryptoHashUtility.cs`

Actual:
`https://github.com/NuGet/NuGet.Client/blob/master//src/NuGet.Core/NuGet.Common/CryptoHashUtility.cs`

NuGet.Client uses the `dev` branch as their default.

**Comment by ljcollins25** [comment]
This might be fixed with 5320461e.
