### ISSUE TITLE
Exclude large files from artifacts

### ISSUE THREAD

**Issue by KirillOsenkov** [Ref12/Codex#148]
We currently include semantic info for very large files in the .zip archive:
![image](https://user-images.githubusercontent.com/679326/51564149-4c1b2400-1e43-11e9-84a2-8c99228ecf2e.png)

Even though they will be excluded from uploading. We shouldn't probably include them in the archive in the first place, even though the compression is great.

**Comment by ljcollins25** [comment]
Fixed.
