### ISSUE TITLE
out var locals highlighting not working

### ISSUE THREAD

**Issue by ljcollins25** [Ref12/Codex#170]
the out parameter localWorkerInfo is not highlighted.

public void AddDirectoryData(uint workerId, DirectoryMembershipHashedEventData data)
        {
            if (workerId != DistributionConstants.LocalWorkerId)
            {
                if (DirectoryData.TryGetValue((DistributionConstants.LocalWorkerId, data.Directory, data.PipId, data.EnumeratePatternRegex), out var **localWorkerInfo**)
                    && localWorkerInfo.EnumeratePatternRegex == data.EnumeratePatternRegex
                    && localWorkerInfo.Directory == data.Directory
                    && localWorkerInfo.IsSearchPath == data.IsSearchPath
                    && localWorkerInfo.IsStatic == data.IsStatic
                    && ListEquals(localWorkerInfo.Members, data.Members))
                {
                    // Don't add data which is redundant with local worker
                    return;
                }
            }

            DirectoryData.GetOrAdd((workerId, data.Directory, data.PipId, data.EnumeratePatternRegex), data);
        }

**Comment by KirillOsenkov** [comment]
Probably needs a Roslyn update and/or a LangVersion=latest setting
