### ISSUE TITLE
Migrate from packages.config to PackageReference

### ISSUE THREAD

**Issue by AArnott** [Ref12/Codex#7]
Would you folks entertain a PR that migrates you to the newer `PackageReference` way of nuget package consumption?

If so, is `master` the right branch to target, or is the monaco branch full of interesting changes that would cause merge conflicts with my proposed change?

**Comment by KirillOsenkov** [comment]
features/monaco has a lot of changes and is the effective master now. Can certainly welcome help but @ljcollins25 needs to decide if we're stable enough for this or if things are still in flux.

**Comment by ljcollins25** [comment]
I don't think we want to go through the effort of going to VS 2017 right now. I'm open to discussing if there are tangible improvements for this project, but as it stands I'd rather just focus on real feature work.

**Comment by AArnott** [comment]
This migration would make working with packages and project files easier. If that doesn't seem worthwhile, feel free to close the issue.

**Comment by KirillOsenkov** [comment]
We'll leave this open because we definitely need to do this at some point. Just waiting for Lance to upgrade to 2017.

**Comment by AArnott** [comment]
@ljcollins25, you're still using VS2015

**Comment by ljcollins25** [comment]
Did this awhile ago. Also mostly using SDK style projects now. A better world indeed.
