### ISSUE TITLE
Check syntax highlighting for C# XML doc comments

### ISSUE THREAD

**Issue by KirillOsenkov** [Ref12/Codex#8]
There's a case here:
http://referencesource.microsoft.com/#System.Drawing/commonui/System/Drawing/ImageAnimator.cs,66

where I can't explain the black spans in the sea of green. Doesn't look like a Roslyn bug. We should try indexing test code with that comment and see if we can repro it.

See also https://github.com/KirillOsenkov/SourceBrowser/issues/79

**Comment by ljcollins25** [comment]
Not an issue in Codex.
