### ISSUE TITLE
Searching doesn't find the symbol that's clearly there

### ISSUE THREAD

**Issue by KirillOsenkov** [Ref12/Codex#91]
The current internally deployed version of Codex has this bug:

1. Search for `IVisualStudioHostProject.I` - you get one result, the `Id` property
2. Search for `IVisualStudioHostProject.Id` - nothing found

We should make sure that this doesn't repro in the new system (and ideally have a test).

**Comment by KirillOsenkov** [comment]
Reported by JasonMal

**Comment by ljcollins25** [comment]
Fixed in new system.
